version: '3.8'

services:
  anxiety-bot:
    build: .
    container_name: anxiety_bot
    restart: unless-stopped
    env_file:
      - .env  # BOT_TOKEN хранится здесь
    volumes:
      - ./users_data.json:/app/users_data.json
